name: build

on:
 pull_request:
   types: [closed]
   branches:
     - main 

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: latest
          lein: latest

      - name: Install dependencies
        run: lein deps

      - name: Leinigen version
        run: lein -v

      - name: Lint!
        run: lein 

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: latest
          lein: latest

      - name: Install dependencies
        run: lein deps

      - name: Leinigen version
        run: lein -v

      - name: Test
        run: lein test
