name: "Run Linters"

on:
  pull_request:
    branches:
      - main

jobs:
  run-linters:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.2
      with:
        cli: latest
        lein: latest

    - name: Install dependencies
      run: lein deps

    - name: Leinigen version
      run: lein -v

    - name: Run linters
      run: lein lint
